// DIR_LOOKUP
void test_dir_lookup_finds_entry(void);
void test_dir_lookup_detects_missing(void);
void test_dir_lookup_skips_invalid_entries(void);
void test_dir_lookup_invalid_inputs(void);
// DIR_EMPTY
void test_dir_empty_returns_true_for_no_entries(void);
void test_dir_empty_returns_true_for_dot_entries(void);
void test_dir_empty_returns_false_for_dir_with_entry(void);
// DIR_ADD
void test_dir_add_fails_when_full(void);
void test_dir_add_fills_first_hole(void);
void test_dir_add_detects_duplicates(void);
void test_dir_add_invalid_inputs(void);
// DIR_REMOVE
void test_dir_remove_rejects_missing_entry(void);
void test_dir_remove_ignores_removed_entries(void);
void test_dir_remove_invalid_inputs(void);
