// INODE_ALLOC
void test_inode_alloc_allocates_first_free_slot(void);
void test_inode_alloc_uses_lowest_available_slot(void);
void test_inode_alloc_preserves_existing_inode_entries(void);
void test_inode_alloc_crosses_inode_table_block_boundary(void);
void test_inode_alloc_returns_failure_when_inode_table_is_full(void);
void test_inode_alloc_invalid_inputs(void);
// INODE_FREE
void test_inode_free_marks_inode_available(void);
void test_inode_free_fails_when_slot_already_free(void);
void test_inode_free_invalid_inputs(void);
// INODE_READ
void test_inode_read_reads_inode_at_requested_slot(void);
void test_inode_read_invalid_inputs(void);
// INODE_WRITE
void test_inode_write_updates_only_requested_inode(void);
void test_inode_write_invalid_inputs(void);
